version: "3.9"

services:
  video-downloader:
    build: .
    container_name: video-downloader
    ports:
      - "5173:80"         # Nginx (frontend)
      - "3000:3000"       # Optional: backend if needed for debugging
    volumes:
      - ./data:/app/data  # Persist downloads
    restart: unless-stopped
